apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fiber-fx-deployment
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: fiber-fx
    spec:
      containers:
        - name: fiber-fx
          image: fiber-fx
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "20m"
              memory: "512Mi"
  selector:
    matchLabels:
      app: fiber-fx
  revisionHistoryLimit: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      # The following pause step will pause the rollout indefinitely until manually resumed.
      # Rollouts can be manually resumed by running `kubectl argo rollouts promote ROLLOUT`
      - pause: {}
      - setWeight: 40
      - pause: {duration: 40s}
      - setWeight: 60
      - pause: {duration: 20s}
      - setWeight: 80
      - pause: {duration: 20s}