apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fiber-fx-deployment
spec:
  replicas: 6
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: fiber-fx
    spec:
      containers:
        - name: fiber-fx
          image: fiber-fx
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "20m"
              memory: "512Mi"
  selector:
    matchLabels:
      app: fiber-fx
  strategy:
    canary:
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause:
          duration: "30s"
      - setWeight: 40
      - pause:
          duration: "30s"
      - setWeight: 80
      - pause:
          duration: "1m"