apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: fiber-fx-deployment
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: fiber-fx
    spec:
      containers:
        - name: fiber-fx
          image: fiber-fx
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "10m"
              memory: "256Mi"
            limits:
              cpu: "20m"
              memory: "512Mi"
  selector:
    matchLabels:
      app: fiber-fx
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary: #Indicates that the rollout should use the Canary strategy
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 30s # 1 hour
      - setWeight: 20
      - pause: {} # pause indefinitely