apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: fiber-fx

images:
- name: fiber-fx
  newName: regiszanandrea/fiber-fx
  newTag: a0aaae1a235f53f4c9113b17d98f1c9d27631702
