apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: fiber-fx

images:
- name: fiber-fx
  newName: regiszanandrea/fiber-fx
  newTag: 7928a6ec7a792db1926728acdbf3518fa5f2f962
