apiVersion: v1
kind: Service
metadata:
  name: stable-fiber-fx-svc
spec:
  ports:
    - name: http-fiber-fx
      port: 9090
      targetPort: 8080
  selector:
    app: fiber-fx
---
apiVersion: v1
kind: Service
metadata:
  name: canary-fiber-fx-svc
spec:
  ports:
    - name: http-fiber-fx
      port: 9090
      targetPort: 8080
  selector:
    app: fiber-fx