name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v4

    - name: test
      run: go test ./...


  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: install dependencies
        run: npm install

      - name: generate release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      