name: Pull Requests
on:
  pull_request:
    branches: [main]
jobs:
  verifications:
    runs-on: ubuntu-latest
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Go
      uses: actions/setup-go@v4

    - name: Run Lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        skip-pkg-cache: true
        skip-build-cache: true

    - name: Run Tests
      run: go test ./...
    
    - name: Run vet
      run: go vet ./...