name: Test
on:
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Install Go
      uses: actions/setup-go@v2

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        skip-go-installation: true
        working-directory: internal

      